# Generated by Django 3.1.7 on 2021-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('rollnumber', models.IntegerField()),
                ('usn', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('dep', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
