# Generated by Django 3.1.7 on 2021-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=100),
        ),
    ]
